const images = {
  tabBarItems: {
    home: require("./tabBarItem/home.png"),
    home_focus: require("./tabBarItem/home_focus.png"),
    note: require("./tabBarItem/note.png"),
    note_focus: require("./tabBarItem/note_focus.png"),
    dictionary: require("./tabBarItem/dictionary.png"),
    dictionary_focus: require("./tabBarItem/dictionary_focus.png"),
    setting: require("./tabBarItem/setting.png"),
    setting_focus: require("./tabBarItem/setting_focus.png"),
  },
  icons: {
    pause_icon: require("./icons/pauseIcon.png"),
    micro_icon: require("./icons/microIcon.png"),
    search_icon: require("./icons/searchIcon.png"),
    arrow_icon: require("./icons/arrowIcon.png"),
    microCircle_icon: require("./icons/microCircleIcon.png"),
    volume_icon: require("./icons/volumeIcon.png"),
    favorite_icon: require("./icons/favoriteIcon.png"),
    history_icon: require("./icons/historyIcon.png"),
    history_disalbe_icon: require("./icons/historyDisableIcon.png"),
    logo_icon: require("./icons/logo.png"),
    add_icon: require("./icons/addIcon.png"),
    default_profileimage: require("./icons/defaultProfileImage.png"),
    rightarrow_icon: require("./icons/rightArrowIcon.png"),
    rightarrow_icon_b: require("./icons/rightArrowIcon_b.png"),
    close_icon: require("./icons/closeIcon.png"),
    leftarrow_icon: require("./icons/leftArrowIcon.png"),
    rightarrow_disable_icon: require("./icons/rightArrowIcon_disable.png"),
    notch_icon: require("./icons/notchIcon.png"),
    speed_icon: require("./icons/speedIcon.png"),
    check_icon: require("./icons/checkedIcon.png"),
    share_icon: require("./icons/shareIcon.png"),
    saved_icon: require("./icons/savedIcon.png"),
    speed_secondary_icon: require("./icons/speedIconSecondary.png"),
    filter_icon: require("./icons/filterIcon.png"),
    search_history_icon: require("./icons/searchHistoryIcon.png"),
    note_icon: require("./icons/noteIcon.png"),
    filter_btn_icon: require("./icons/filterbtnIcon.png"),
    non_favorite_icon: require("./icons/nonfavoriteIcon.png"),
    compare_icon: require("./icons/compareIcon.png"),
    favorited_icon: require("./icons/favoritedIcon.png"),
    favorited_disable_icon: require("./icons/favoritedDisableIcon.png"),
    delete_icon: require("./icons/deleteIcon.png"),
    edit_icon: require("./icons/editIcon.png"),
    knob_icon: require("./icons/knobIcon.png"),
    next_icon: require("./icons/nextIcon.png"),
    previous_icon: require("./icons/previousIcon.png"),
    play_icon: require("./icons/playIcon.png"),
    launch_icon: require("./icons/launchIcon.png"),
    facebook_icon: require("./icons/facebookIcon.png"),
    checkbox_icon: require("./icons/checkIcon.png"),
    progressbar_1_icon: require("./icons/progressbar1Icon.png"),
    progressbar_2_icon: require("./icons/progressbar2Icon.png"),
    progressbar_3_icon: require("./icons/progressbar3Icon.png"),
    success_icon: require("./icons/successIcon.png"),
    comment_icon: require("./icons/commentIcon.png"),
    check_black_icon: require("./icons/checkBlackIcon.png"),
    remove_icon: require("./icons/remove.png"),
    disable_play_icon: require("./icons/disablePlayIcon.png"),
    disable_next_icon: require("./icons/disableNextIcon.png"),
    disable_previous_icon: require("./icons/disablePreviousIcon.png"),
    push_pin_icon: require("./icons/pushpinIcon.png"),
    push_pin_selected_icon: require("./icons/pushpinSelectedIcon.png"),
  },
};

export default images;
